### ISSUE TITLE
Exception not correctly resolved in async tests

### ISSUE THREAD

**Issue by KQuinn1996** [SimonCropp/XunitContext#109]

**Comment by SimonCropp** [comment]
can you submit a failing test as a PullRequest

**Comment by KQuinn1996** [comment]
Apologies, it isn't ClassData that is the issue, my test being async is what causes the exception to be null. 

When it is not async it works perfect. I have a some code examples of this being the case if you wish for me to do that PR?

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
