### ISSUE TITLE
[BUG] Microsoft.Extensions.Logging.Console Console logs not captured - limitation of Context.Write overloads

### ISSUE THREAD

**Issue by thargy** [SimonCropp/XunitContext#168]
#### Describe the bug

When using `Microsoft.Extensions.Logging.Console`, logs that are written to the Console are not collected by the Context correctly.  For example:
```csharp
    public class ConsoleLogTest : XunitContextBase
    {
        /// <inheritdoc />
        public ConsoleLogTest(ITestOutputHelper output) : base(output)
        {
        }

        [Fact]
        public void ShowIssue()
        {
            using var loggerFactory = LoggerFactory.Create(builder => builder.AddConsole());
            var logger =loggerFactory.CreateLogger<ConsoleLogTest>();
            logger.LogInformation("Log information");

            // FAILS
            Assert.Equal(1, Logs.Count);
        }
    }
```

There are two issues, the first is due to log buffering, this can be overcome by disposing of the logger factory prior to checking for output, as this flushes logs, e.g.
```csharp
    public class ConsoleLogTest : XunitContextBase
    {
        /// <inheritdoc />
        public ConsoleLogTest(ITestOutputHelper output) : base(output)
        {
        }

        [Fact]
        public void ShowIssue()
        {
            using (var loggerFactory = LoggerFactory.Create(builder => builder.AddConsole()))
            {
                var logger =loggerFactory.CreateLogger<ConsoleLogTest>();
                logger.LogInformation("Log information");
            }
            // STILL FAILS - even though Console has always been logged to at this point
            Assert.Equal(1, Logs.Count);
        }
    }
```

In the minimal repro, I have confirmed that logs are written using an interception:
```csharp
        [Fact]
        public void Test1()
        {
            // Intercept Console just wraps a text writer and counts invocations of write methods.
            var interceptConsole = new InterceptConsole(Console.Out);
            Console.SetOut(interceptConsole);
            using (var loggerFactory = LoggerFactory.Create(builder => builder.AddConsole()))
            {
                var logger = loggerFactory.CreateLogger<ConsoleLogTest>();
                logger.LogInformation("Log information");
            } // disposing logger factory actually flushes it

            // Console logger makes two Write() calls
            Assert.Equal(2, interceptConsole.WriteCount);

            // FAILS
            Assert.Equal(1, Logs.Count);
        }
```

Although disposing of the loggerFactory explicitly to force log flushing is a bit of code smell, it is probably the only acceptable approach to reliably detect logs using the console logger. 

However, _this still fails_.  After much tracing, I believe it is due to the way that the console logger never actually calls `WriteLine` (see [this code](https://github.com/aspnet/Logging/blob/2d2f31968229eddb57b6ba3d34696ef366a6c71b/src/Microsoft.Extensions.Logging.Console/Internal/ConsoleLoggerProcessor.cs#L48-L64)), instead it passes newline characters directly to the write methods.

I believe this is a limitation in the current implementation of [`Context.Write`](https://github.com/SimonCropp/XunitContext/blob/469e37fc7a6f918b3546b84dff7d6f1f1bf2ecec/src/XunitContext/Context.cs#L107-L138) which should detect and split on new line characters and add [`logMessages`](https://github.com/SimonCropp/XunitContext/blob/469e37fc7a6f918b3546b84dff7d6f1f1bf2ecec/src/XunitContext/Context.cs#L107-L138).

#### Minimal Repro

I have created a minimal repo for your convenience at https://github.com/thargy/XUnitContextConsoleTest.

**Comment by thargy** [comment]
Anyone finding this issue that would like a simple way to use `Microsoft.Logging.Extensions.ILogger` with this library may be interested in the following gist that I threw together.  It doesn't support the full `Microsoft.Logging.Extensions` pattern (i.e. a logger provider, etc.), but it does allow for easy creation of `ILogger` and `ILogger<T>` and allows immediate testing of `LogEntry`s (which have full information rather than just lines.

[TestBase.cs](https://gist.github.com/thargy/81623e64836d9c5b55094b5577996737)

To use, have your class descend from `TestsBase`, e.g.
```csharp
    public sealed class Tests : TestsBase
    {
        public Tests (ITestOutputHelper outputHelper) : base(outputHelper)
        {
        }        

		[Fact]
        public void Test1()
        {
			var acceptsILogger = new MyClass(Logger);
            acceptsILogger.DoSomethingThatLogsWarning();

            // Check for warning
            Assert.Equal(1, LogEntryCount);
            var lastLog = LogEntries.Last();
            Assert.Equal(LogLevel.Warning, lastLog.LogLevel);
            Assert.Equal("A warning.", lastLog.Message);
        }

		[Fact]
        public void Test2()
        {
			var acceptsILoggerT = new MyClass(GetLogger<MyClass>());
            acceptsILoggerT.DoSomethingThatLogsWarning();
            ...
        }
    }
```

This is a much cleaner/quicker way to test logs when using this library with `Microsoft.Logging.Extensions.ILogger`, and doesn't suffer from flushing issues.

**Comment by SimonCropp** [comment]
let me know via a PR if you come up with a fix

**Comment by thargy** [comment]
PR created.  Also addresses an existing bug with extra newlines in output and trailing newline characters on some (but not all) entries in LogMessages collection.  Handles `\n` and `\r\n` newline standards.
