### ISSUE TITLE
Capture Exception in context

### ISSUE THREAD

**Issue by ildmth** [SimonCropp/XunitContext#329]
I tried this code and it works as in example with Assert:

```
 public override void Dispose()
    {
        var theExceptionThrownByTest = Context.TestException;
        var testDisplayName = Context.Test.DisplayName;
        var testCase = Context.Test.TestCase;
        base.Dispose();
    }
```
But what if real exception thrown in test, e.g. NullReference? e.g. throw new Exception("test");
It is null in context in dispose, could we capture it?

**Comment by SimonCropp** [comment]
i dont understand what you are asking

**Comment by FourTwoOmega** [comment]
I'm having the same issue. When I reference Context.TestException in a Dispose() method, it's always null, even if an exception was thrown.

**Comment by SimonCropp** [comment]
i cant repro this. can u submit a repro as a pull request

**Comment by SimonCropp** [comment]
also just to confirm, you have this in a module init

```

public static class GlobalSetup
{
    [ModuleInitializer]
    public static void Setup() =>
        XunitContext.EnableExceptionCapture();
}
```

**Comment by FourTwoOmega** [comment]
That was it! Glad it was something dumb and not a bug. Thank you

![image](https://user-images.githubusercontent.com/13643768/159102708-8d4a7d18-540b-47f5-954f-1bed6b1b7504.png)

**Comment by FourTwoOmega** [comment]
By the way, thank you so much for this package. You saved me from having to re-do all my tests in NUnit when I discovered I couldn't get the name of the current test

**Comment by SimonCropp** [comment]
an exception will now be thrown if EnableExceptionCapture is not called
