### ISSUE TITLE
Context.Exception ignores regular exceptions

### ISSUE THREAD

**Issue by ThreePinkApples** [SimonCropp/XunitContext#335]
I've been testing out XunitContext today to implement a failfast behaviour in my integration tests, and ended up spending tons of time trying to figure out why it sometimes captured exceptions and sometimes didn't, just to look at the source and see that it only returns XunitException and some aggregated exceptions.

What if a test fails with some regular exception? Such a System.TimeoutException which is the one I had now, or just some other exception. Those are equally valid as test failure as an XunitException from an assert method.
After discovering this it was a quick workaround to just wrap that underlying helper method with try/except and throw XunitException but should that be necessary?

**Comment by SimonCropp** [comment]
can you share a failing unit test as a PR

**Comment by ThreePinkApples** [comment]
The unit tests are not passing (even before my changes), but I created a PR #336
