### ISSUE TITLE
ITestOutputHelper already registered - Ubuntu only?

### ISSUE THREAD

**Issue by angularsen** [SimonCropp/XunitContext#338]
#### Describe the bug

Added `XunitContextBase` as base class of our integration tests to format exceptions. Enabled exception tracking with module initializer.

**Problem:** 
On CI builds running `ubuntu-20.04` on Azure DevOps many tests failed with exception: `A ITestOutputHelper has already been registered.` No obvious pattern to red vs green tests.

All tests were green when run locally on Windows with both JetBrains Rider and `dotnet test` test runners.

**Theory:**
The exception is raised by `Xunit.XunitContext.Register()` in `XunitContextBase.ctor()`.
It relies on `AsyncLocal` to determine if already initialized.

Is this maybe a Windows vs Ubuntu issue?
Have you seen this before?

**Workaround**
We mimiced the FirstChanceException tracking in our own base class and simply stored it as a field, without using AsyncLocal.

**Setup:**
- ModuleInitializer in MyHelperProject
- MyTestBase class in MyHelperProject
- TestClassA -> MyTestBase -> XunitContextBase
- Test projects target `net6.0` and latest xunit

#### Minimal Repro

Not yet.

**Comment by SimonCropp** [comment]
> Is this maybe a Windows vs Ubuntu issue?

unlikely, but possible

> Have you seen this before?

nope

It will be pretty difficult to work out what the issue is without a repro

I pushed a 3.2.5 to nuget that includes the existing source file in the "ITestOutputHelper has already been registered" exception. It might help us debug

**Comment by angularsen** [comment]
I tried to set up a minimal repro, but have not been successful. I don't have time to investigate further since I found a workaround we are happy with. 

It may very well be some quirk with our integration test setup combined with AsyncLocal.
Closing this issue.

Link for future reference:
https://github.com/angularsen/XunitContext-338-repro

**Comment by jspuij** [comment]
I have exactly the same issue on macOS while trying to use XUnitContext to implement a playwright base class to do End to End test. I'll try to get a stack trace and an async call log to investigate.

What I suspect is, that multiple test constructors are executed within the same call context to prepare for test execution, hence that this occurs.

**Comment by SimonCropp** [comment]
@Barsonax happy to reopen. can you submit a PR with a failing unit test to get us started
